// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhoLaF00l9mLCV9xs8nwtWJu0l3g6_rzM',
    appId: '1:935784625448:web:288143837aacb47daa0c1d',
    messagingSenderId: '935784625448',
    projectId: 'polls-b96a4',
    authDomain: 'polls-b96a4.firebaseapp.com',
    storageBucket: 'polls-b96a4.appspot.com',
    measurementId: 'G-7E19R2HDP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0MAbXdXMi7RAwBy-hX5z_K5__tkD5XTw',
    appId: '1:935784625448:android:5135ba77f98203cdaa0c1d',
    messagingSenderId: '935784625448',
    projectId: 'polls-b96a4',
    storageBucket: 'polls-b96a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJEAuuRshI8v79T5SnVmORxuwbAksyFc',
    appId: '1:935784625448:ios:36d789f2ebdf25f5aa0c1d',
    messagingSenderId: '935784625448',
    projectId: 'polls-b96a4',
    storageBucket: 'polls-b96a4.appspot.com',
    iosClientId:
        '935784625448-8s18hrdj5l12v7mlas890n53pejq91mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.poll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJEAuuRshI8v79T5SnVmORxuwbAksyFc',
    appId: '1:935784625448:ios:36d789f2ebdf25f5aa0c1d',
    messagingSenderId: '935784625448',
    projectId: 'polls-b96a4',
    storageBucket: 'polls-b96a4.appspot.com',
    iosClientId:
        '935784625448-8s18hrdj5l12v7mlas890n53pejq91mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.poll',
  );
}
